// VYTAL Fitness — Premium Cyan/Blue dark theme
const colors = {
  dark: {
    text: '#FFFFFF',
    tint: '#00F0FF',
    background: '#070A12',
    foreground: '#FFFFFF',
    card: '#0F172A',
    cardForeground: '#FFFFFF',
    primary: '#00F0FF',
    primaryForeground: '#000000',
    secondary: '#0066FF',
    secondaryForeground: '#FFFFFF',
    muted: '#1E293B',
    mutedForeground: '#718096',
    accent: '#8B5CF6',
    accentForeground: '#FFFFFF',
    destructive: '#FF4D4D',
    destructiveForeground: '#FFFFFF',
    border: '#1E293B',
    input: '#1E293B',
    gradientStart: '#00F0FF',
    gradientEnd: '#0066FF',
  },
  light: {
    text: '#060A14',
    tint: '#0061FF',
    background: '#F0F4FF',
    foreground: '#060A14',
    card: '#FFFFFF',
    cardForeground: '#060A14',
    primary: '#0061FF',
    primaryForeground: '#FFFFFF',
    secondary: '#00AACC',
    secondaryForeground: '#FFFFFF',
    muted: '#E8EEF8',
    mutedForeground: '#506070',
    accent: '#6D28D9',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#D4DDF0',
    input: '#D4DDF0',
    gradientStart: '#0061FF',
    gradientEnd: '#00AACC',
  },
  radius: 14,
};

export default colors;
