// VYTAL Fitness — Premium Cyan/Blue dark theme
const colors = {
  dark: {
    text: '#FFFFFF',
    tint: '#00D4FF',
    background: '#060A14',
    foreground: '#FFFFFF',
    card: '#0D1526',
    cardForeground: '#FFFFFF',
    primary: '#00D4FF',
    primaryForeground: '#000000',
    secondary: '#0061FF',
    secondaryForeground: '#FFFFFF',
    muted: '#111B2E',
    mutedForeground: '#607090',
    accent: '#7C3AED',
    accentForeground: '#FFFFFF',
    destructive: '#FF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1A2740',
    input: '#1A2740',
    gradientStart: '#00D4FF',
    gradientEnd: '#0061FF',
  },
  light: {
    text: '#060A14',
    tint: '#0061FF',
    background: '#F0F4FF',
    foreground: '#060A14',
    card: '#FFFFFF',
    cardForeground: '#060A14',
    primary: '#0061FF',
    primaryForeground: '#FFFFFF',
    secondary: '#00AACC',
    secondaryForeground: '#FFFFFF',
    muted: '#E8EEF8',
    mutedForeground: '#506070',
    accent: '#6D28D9',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#D4DDF0',
    input: '#D4DDF0',
    gradientStart: '#0061FF',
    gradientEnd: '#00AACC',
  },
  radius: 14,
};

export default colors;
